"""recipes and tags

Revision ID: ebf85f6b760c
Revises: 76cb79d76f1d
Create Date: 2021-01-14 14:07:02.304622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf85f6b760c'
down_revision = '76cb79d76f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('recipeId', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'tags', ['recipeId'])
    op.create_foreign_key(None, 'tags', 'recipes', ['recipeId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_column('tags', 'recipeId')
    # ### end Alembic commands ###
